"""Add ClassSchedule model and relationship to SubjectClass

Revision ID: 2f94c0acbf6b
Revises: 44ba0bb796ca
Create Date: 2025-05-13 02:18:50.738801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f94c0acbf6b'
down_revision = '44ba0bb796ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_class_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_class_id'], ['subject_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_unique_constraint('_student_class_date_session_uc', ['student_id', 'subject_class_id', 'date', 'session_time'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_constraint('_student_class_date_session_uc', type_='unique')

    op.drop_table('class_schedules')
    # ### end Alembic commands ###
